'\" t
.\"     Title: pam-config
.\"    Author: [see the "AUTHOR" section]
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: 04/02/2014
.\"    Manual: Reference Manual
.\"    Source: Reference Manual
.\"  Language: English
.\"
.TH "PAM\-CONFIG" "8" "04/02/2014" "Reference Manual" "Reference Manual"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
pam-config \- Adjust common PAM config files
.SH "SYNOPSIS"
.HP \w'\fBpam\-config\fR\ 'u
\fBpam\-config\fR [\-\-debug] [\-\-list\-modules] [\-\-service\ \fIservice\-name\fR] \-a | \-c | \-d | \-q  [\-f] [\fImodule\-name\fR]
.HP \w'\fBpam\-config\fR\ 'u
\fBpam\-config\fR \-\-version
.SH "DESCRIPTION"
.PP
\fBpam\-config\fR
adjusts predefined PAM config files\&.
.SH "OPTIONS"
.SS "COMMON OPTIONS"
.PP
\fB\-\-debug\fR
.RS 4
Print debug messages\&.
.RE
.PP
\fB\-f\fR, \fB\-\-force\fR
.RS 4
The new configuration will be activated regardless if there are other local changes\&.
.RE
.PP
\fB\-\-list\-modules\fR
.RS 4
Prints out a list of all supported modules to stdout\&.
.RE
.PP
\fB\-\-nullok\fR
.RS 4
Add
\fBnullok\fR
to all modules which support this\&.
.RE
.PP
\fB\-\-pam\-debug\fR
.RS 4
Add
\fBdebug\fR
to all modules which support this\&.
.RE
.SS "MODIFIER OPTIONS"
.PP
Use the following options to specifiy the action you want pam\-config to apply\&. They need to be followed by a supported module option\&. See
the section called \(lqSUPPORTED PAM MODULES\(rq\&.
.PP
\fB\-a\fR, \fB\-\-add\fR
.RS 4
Add options or new PAM modules to existing PAM configuration files\&.
.RE
.PP
\fB\-c\fR, \fB\-\-create\fR
.RS 4
Create new PAM configuration files for plain UNIX authentication, overwriting existing ones\&.
.RE
.PP
\fB\-d\fR, \fB\-\-delete\fR
.RS 4
Remove options or PAM modules from existing PAM configuration files\&.
.RE
.PP
\fB\-q\fR, \fB\-\-query\fR
.RS 4
Print a list of types and the corresponding module options for the queried PAM module\&.
.RE
.PP
\fB\-\-verify\fR
.RS 4
Do some sanity checks on the current common PAM configuration files\&.
.RE
.SS "SUPPORTED PAM MODULES"
.PP
This is a list of modules supported by pam\-config\&. They are split into two categories: global and single service modules\&.
.sp
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
.ps +1
\fBGLOBAL MODULES\fR
.RS 4
.PP
The global modules get inserted into the common\-{account,auth,password,session} files which are included by the single service files\&.
.PP
\fB\-\-access\fR
.RS 4
pam_access for account access rules
.RE
.PP
\fB\-\-access\-debug\fR
.RS 4
Add
\fBdebug\fR
option to all pam_access\&.so invocations\&.
.RE
.PP
\fB\-\-access\-nodefgroup\fR
.RS 4
Add
\fBnodefgroup\fR
option to all pam_access\&.so invocations\&.
.RE
.PP
\fB\-\-access\-noaudit\fR
.RS 4
Add
\fBnoaudit\fR
option to all pam_access\&.so invocations\&.
.RE
.PP
\fB\-\-access\-accessfile=\fR\fIvalue\fR
.RS 4
Add
\fBaccessfile=\fR\fIvalue\fR
option to pam_access\&.so\&.
.RE
.PP
\fB\-\-access\-fieldsep=\fR\fIvalue\fR
.RS 4
Add
\fBfieldsep=\fR\fIvalue\fR
option to pam_access\&.so\&.
.RE
.PP
\fB\-\-access\-listsep=\fR\fIvalue\fR
.RS 4
Add
\fBlistsep=\fR\fIvalue\fR
option to pam_access\&.so\&.
.RE
.PP
\fB\-\-apparmor\fR
.RS 4
Enable/Disable pam_apparmor\&.so
.RE
.PP
\fB\-\-apparmor\-debug\fR
.RS 4
Add
\fBdebug\fR
option to all pam_apparmor\&.so invocations\&.
.RE
.PP
\fB\-\-ccreds\fR
.RS 4
Enable/Disable pam_ccreds\&.so
.RE
.PP
\fB\-\-cracklib\fR
.RS 4
Enable/Disable pam_cracklib\&.so
.RE
.PP
\fB\-\-cracklib\-debug\fR
.RS 4
Add
\fBdebug\fR
option to all pam_cracklib\&.so invocations\&.
.RE
.PP
\fB\-\-cracklib\-authtok_type=\fR\fIvalue\fR
.RS 4
Add
\fBauthtok_type=\fR\fIvalue\fR
option to pam_cracklib\&.so\&.
.RE
.PP
\fB\-\-cracklib\-retry=\fR\fIvalue\fR
.RS 4
Add
\fBretry=\fR\fIvalue\fR
option to pam_cracklib\&.so\&.
.RE
.PP
\fB\-\-cracklib\-difok=\fR\fIvalue\fR
.RS 4
Add
\fBdifok=\fR\fIvalue\fR
option to pam_cracklib\&.so\&.
.RE
.PP
\fB\-\-cracklib\-difignore=\fR\fIvalue\fR
.RS 4
Add
\fBdifignore=\fR\fIvalue\fR
option to pam_cracklib\&.so\&.
.RE
.PP
\fB\-\-cracklib\-minlen=\fR\fIvalue\fR
.RS 4
Add
\fBminlen=\fR\fIvalue\fR
option to pam_cracklib\&.so\&.
.RE
.PP
\fB\-\-cracklib\-dcredit=\fR\fIvalue\fR
.RS 4
Add
\fBdcredit=\fR\fIvalue\fR
option to pam_cracklib\&.so\&.
.RE
.PP
\fB\-\-cracklib\-ucredit=\fR\fIvalue\fR
.RS 4
Add
\fBucredit=\fR\fIvalue\fR
option to pam_cracklib\&.so\&.
.RE
.PP
\fB\-\-cracklib\-lcredit=\fR\fIvalue\fR
.RS 4
Add
\fBlcredit=\fR\fIvalue\fR
option to pam_cracklib\&.so\&.
.RE
.PP
\fB\-\-cracklib\-ocredit=\fR\fIvalue\fR
.RS 4
Add
\fBocredit=\fR\fIvalue\fR
option to pam_cracklib\&.so\&.
.RE
.PP
\fB\-\-cracklib\-minclass=\fR\fIvalue\fR
.RS 4
Add
\fBminclass=\fR\fIvalue\fR
option to pam_cracklib\&.so\&.
.RE
.PP
\fB\-\-cracklib\-dictpath=\fR\fIvalue\fR
.RS 4
Add
\fBdictpath=\fR\fIvalue\fR
option to pam_cracklib\&.so\&.
.RE
.PP
\fB\-\-ecryptfs\fR
.RS 4
Enable/Disable pam_ecryptfs\&.so
.RE
.PP
\fB\-\-ecryptfs\-unwrap\fR
.RS 4
Add
\fBunwrap\fR
option to all pam_ecryptfs\&.so invocations\&.
.RE
.PP
\fB\-\-env\fR
.RS 4
Enable/Disable pam_env\&.so
.RE
.PP
\fB\-\-env\-debug\fR
.RS 4
Add
\fBdebug\fR
option to all pam_env\&.so invocations\&.
.RE
.PP
\fB\-\-env\-conffile=\fR\fIvalue\fR
.RS 4
Add
\fBconffile=\fR\fIvalue\fR
option to pam_env\&.so\&.
.RE
.PP
\fB\-\-env\-envfile=\fR\fIvalue\fR
.RS 4
Add
\fBenvfile=\fR\fIvalue\fR
option to pam_env\&.so\&.
.RE
.PP
\fB\-\-env\-readenv=\fR\fIvalue\fR
.RS 4
Add
\fBreadenv=\fR\fIvalue\fR
option to pam_env\&.so\&.
.RE
.PP
\fB\-\-exec\fR
.RS 4
pam_exec for password management
.RE
.PP
\fB\-\-exec\-debug\fR
.RS 4
Add
\fBdebug\fR
option to all pam_exec\&.so invocations\&.
.RE
.PP
\fB\-\-exec\-expose_authtok\fR
.RS 4
Add
\fBexpose_authtok\fR
option to all pam_exec\&.so invocations\&.
.RE
.PP
\fB\-\-exec\-seteuid\fR
.RS 4
Add
\fBseteuid\fR
option to all pam_exec\&.so invocations\&.
.RE
.PP
\fB\-\-exec\-quiet\fR
.RS 4
Add
\fBquiet\fR
option to all pam_exec\&.so invocations\&.
.RE
.PP
\fB\-\-exec\-log=\fR\fIvalue\fR
.RS 4
Add
\fBlog=\fR\fIvalue\fR
option to pam_exec\&.so\&.
.RE
.PP
\fB\-\-exec\-option=\fR\fIvalue\fR
.RS 4
Add
\fBoption=\fR\fIvalue\fR
option to pam_exec\&.so\&.
.RE
.PP
\fB\-\-fp\fR
.RS 4
Enable/Disable pam_fp\&.so
.RE
.PP
\fB\-\-fp\-debug\fR
.RS 4
Add
\fBdebug\fR
option to all pam_fp\&.so invocations\&.
.RE
.PP
\fB\-\-fprint\fR
.RS 4
Enable/Disable pam_fprint\&.so
.RE
.PP
\fB\-\-fprint\-debug\fR
.RS 4
Add
\fBdebug\fR
option to all pam_fprint\&.so invocations\&.
.RE
.PP
\fB\-\-fprintd\fR
.RS 4
Enable/Disable pam_fprintd\&.so
.RE
.PP
\fB\-\-fprintd\-debug\fR
.RS 4
Add
\fBdebug\fR
option to all pam_fprintd\&.so invocations\&.
.RE
.PP
\fB\-\-gnome_keyring\fR
.RS 4
Enable/Disable pam_gnome_keyring\&.so
.RE
.PP
\fB\-\-gnome_keyring\-auto_start\fR
.RS 4
Add
\fBauto_start\fR
option to all pam_gnome_keyring\&.so invocations\&.
.RE
.PP
\fB\-\-gnome_keyring\-only_if=\fR\fIvalue\fR
.RS 4
Add
\fBonly_if=\fR\fIvalue\fR
option to pam_gnome_keyring\&.so\&.
.RE
.PP
\fB\-\-group\fR
.RS 4
Enable/Disable pam_group\&.so
.RE
.PP
\fB\-\-krb5\fR
.RS 4
Enable/Disable pam_krb5\&.so
.RE
.PP
\fB\-\-krb5\-debug\fR
.RS 4
Add
\fBdebug\fR
option to all pam_krb5\&.so invocations\&.
.RE
.PP
\fB\-\-krb5\-ignore_unknown_principals\fR
.RS 4
Add
\fBignore_unknown_principals\fR
option to all pam_krb5\&.so invocations\&.
.RE
.PP
\fB\-\-krb5\-minimum_uid=\fR\fIvalue\fR
.RS 4
Add
\fBminimum_uid=\fR\fIvalue\fR
option to pam_krb5\&.so\&.
.RE
.PP
\fB\-\-ldap\fR
.RS 4
Enable/Disable pam_ldap\&.so
.RE
.PP
\fB\-\-ldap\-debug\fR
.RS 4
Add
\fBdebug\fR
option to all pam_ldap\&.so invocations\&.
.RE
.PP
\fB\-\-limits\fR
.RS 4
Enable/Disable pam_limits\&.so
.RE
.PP
\fB\-\-limits\-debug\fR
.RS 4
Add
\fBdebug\fR
option to all pam_limits\&.so invocations\&.
.RE
.PP
\fB\-\-limits\-change_uid\fR
.RS 4
Add
\fBchange_uid\fR
option to all pam_limits\&.so invocations\&.
.RE
.PP
\fB\-\-limits\-utmp_early\fR
.RS 4
Add
\fButmp_early\fR
option to all pam_limits\&.so invocations\&.
.RE
.PP
\fB\-\-limits\-conf=\fR\fIvalue\fR
.RS 4
Add
\fBconf=\fR\fIvalue\fR
option to pam_limits\&.so\&.
.RE
.PP
\fB\-\-localuser\fR
.RS 4
Enable/Disable pam_localuser\&.so
.RE
.PP
\fB\-\-localuser\-debug\fR
.RS 4
Add
\fBdebug\fR
option to all pam_localuser\&.so invocations\&.
.RE
.PP
\fB\-\-localuser\-file=\fR\fIvalue\fR
.RS 4
Add
\fBfile=\fR\fIvalue\fR
option to pam_localuser\&.so\&.
.RE
.PP
\fB\-\-mkhomedir\fR
.RS 4
Enable/Disable pam_mkhomedir\&.so
.RE
.PP
\fB\-\-mkhomedir\-debug\fR
.RS 4
Add
\fBdebug\fR
option to all pam_mkhomedir\&.so invocations\&.
.RE
.PP
\fB\-\-mkhomedir\-silent\fR
.RS 4
Add
\fBsilent\fR
option to all pam_mkhomedir\&.so invocations\&.
.RE
.PP
\fB\-\-mkhomedir\-umask=\fR\fIvalue\fR
.RS 4
Add
\fBumask=\fR\fIvalue\fR
option to pam_mkhomedir\&.so\&.
.RE
.PP
\fB\-\-mkhomedir\-skel=\fR\fIvalue\fR
.RS 4
Add
\fBskel=\fR\fIvalue\fR
option to pam_mkhomedir\&.so\&.
.RE
.PP
\fB\-\-nam\fR
.RS 4
Enable/Disable pam_nam\&.so
.RE
.PP
\fB\-\-passwdqc\fR
.RS 4
Enable/Disable pam_passwdqc\&.so
.RE
.PP
\fB\-\-passwdqc\-ask_oldauthtok\fR
.RS 4
Add
\fBask_oldauthtok\fR
option to all pam_passwdqc\&.so invocations\&.
.RE
.PP
\fB\-\-passwdqc\-check_oldauthtok\fR
.RS 4
Add
\fBcheck_oldauthtok\fR
option to all pam_passwdqc\&.so invocations\&.
.RE
.PP
\fB\-\-passwdqc\-use_first_pass\fR
.RS 4
Add
\fBuse_first_pass\fR
option to all pam_passwdqc\&.so invocations\&.
.RE
.PP
\fB\-\-passwdqc\-use_authtok\fR
.RS 4
Add
\fBuse_authtok\fR
option to all pam_passwdqc\&.so invocations\&.
.RE
.PP
\fB\-\-passwdqc\-min=\fR\fIvalue\fR
.RS 4
Add
\fBmin=\fR\fIvalue\fR
option to pam_passwdqc\&.so\&.
.RE
.PP
\fB\-\-passwdqc\-max=\fR\fIvalue\fR
.RS 4
Add
\fBmax=\fR\fIvalue\fR
option to pam_passwdqc\&.so\&.
.RE
.PP
\fB\-\-passwdqc\-passphrase=\fR\fIvalue\fR
.RS 4
Add
\fBpassphrase=\fR\fIvalue\fR
option to pam_passwdqc\&.so\&.
.RE
.PP
\fB\-\-passwdqc\-match=\fR\fIvalue\fR
.RS 4
Add
\fBmatch=\fR\fIvalue\fR
option to pam_passwdqc\&.so\&.
.RE
.PP
\fB\-\-passwdqc\-similar=\fR\fIvalue\fR
.RS 4
Add
\fBsimilar=\fR\fIvalue\fR
option to pam_passwdqc\&.so\&.
.RE
.PP
\fB\-\-passwdqc\-random=\fR\fIvalue\fR
.RS 4
Add
\fBrandom=\fR\fIvalue\fR
option to pam_passwdqc\&.so\&.
.RE
.PP
\fB\-\-passwdqc\-enforce=\fR\fIvalue\fR
.RS 4
Add
\fBenforce=\fR\fIvalue\fR
option to pam_passwdqc\&.so\&.
.RE
.PP
\fB\-\-passwdqc\-retry=\fR\fIvalue\fR
.RS 4
Add
\fBretry=\fR\fIvalue\fR
option to pam_passwdqc\&.so\&.
.RE
.PP
\fB\-\-pkcs11\fR
.RS 4
Enable/Disable pam_pkcs11\&.so
.RE
.PP
\fB\-\-pkcs11\-debug\fR
.RS 4
Add
\fBdebug\fR
option to all pam_pkcs11\&.so invocations\&.
.RE
.PP
\fB\-\-pkcs11\-configfile=\fR\fIvalue\fR
.RS 4
Add
\fBconfigfile=\fR\fIvalue\fR
option to pam_pkcs11\&.so\&.
.RE
.PP
\fB\-\-pwcheck\fR
.RS 4
Enable/Disable pam_pwcheck\&.so module in password section\&.
.RE
.PP
\fB\-\-pwcheck\-debug\fR
.RS 4
Add
\fBdebug\fR
option to all pam_pwcheck\&.so invocations\&.
.RE
.PP
\fB\-\-pwcheck\-nullok\fR
.RS 4
Add
\fBnullok\fR
option to all pam_pwcheck\&.so invocations\&.
.RE
.PP
\fB\-\-pwcheck\-cracklib\fR
.RS 4
Add
\fBcracklib\fR
option to pam_pwcheck\&.so\&.
.RE
.PP
\fB\-\-pwcheck\-no_obscure_checks\fR
.RS 4
Add
\fBno_obscure_checks\fR
option to pam_pwcheck\&.so\&.
.RE
.PP
\fB\-\-pwcheck\-enforce_for_root\fR
.RS 4
Add
\fBenforce_for_root\fR
option to pam_pwcheck\&.so\&.
.RE
.PP
\fB\-\-pwcheck\-cracklib_path=\fR\fIpath\fR
.RS 4
Add
\fBcracklib_path=\fR\fIpath\fR
to pam_pwcheck\&.so\&.
.RE
.PP
\fB\-\-pwcheck\-maxlen=\fR\fIN\fR
.RS 4
Add
\fBmaxlen=\fR\fIN\fR
to pam_pwcheck\&.so\&.
.RE
.PP
\fB\-\-pwcheck\-minlen=\fR\fIN\fR
.RS 4
Add
\fBminlen=\fR\fIN\fR
to pam_pwcheck\&.so\&.
.RE
.PP
\fB\-\-pwcheck\-tries=\fR\fIN\fR
.RS 4
Add
\fBtries=\fR\fIN\fR
to pam_pwcheck\&.so\&.
.RE
.PP
\fB\-\-pwcheck\-remember=\fR\fIN\fR
.RS 4
Add
\fBremember=\fR\fIN\fR
to pam_pwcheck\&.so\&.
.RE
.PP
\fB\-\-pwhistory\fR
.RS 4
Enable/Disable pam_pwhistory\&.so
.RE
.PP
\fB\-\-pwhistory\-debug\fR
.RS 4
Add
\fBdebug\fR
option to all pam_pwhistory\&.so invocations\&.
.RE
.PP
\fB\-\-pwhistory\-use_authtok\fR
.RS 4
Add
\fBuse_authtok\fR
option to all pam_pwhistory\&.so invocations\&.
.RE
.PP
\fB\-\-pwhistory\-enforce_for_root\fR
.RS 4
Add
\fBenforce_for_root\fR
option to all pam_pwhistory\&.so invocations\&.
.RE
.PP
\fB\-\-pwhistory\-remember=\fR\fIvalue\fR
.RS 4
Add
\fBremember=\fR\fIvalue\fR
option to pam_pwhistory\&.so\&.
.RE
.PP
\fB\-\-pwhistory\-retry=\fR\fIvalue\fR
.RS 4
Add
\fBretry=\fR\fIvalue\fR
option to pam_pwhistory\&.so\&.
.RE
.PP
\fB\-\-pwhistory\-authtok_type=\fR\fIvalue\fR
.RS 4
Add
\fBauthtok_type=\fR\fIvalue\fR
option to pam_pwhistory\&.so\&.
.RE
.PP
\fB\-\-selinux\fR
.RS 4
Enable/Disable pam_selinux\&.so
.RE
.PP
\fB\-\-selinux\-debug\fR
.RS 4
Add
\fBdebug\fR
option to all pam_selinux\&.so invocations\&.
.RE
.PP
\fB\-\-ssh\fR
.RS 4
Enable/Disable pam_ssh\&.so
.RE
.PP
\fB\-\-ssh\-debug\fR
.RS 4
Add
\fBdebug\fR
option to all pam_ssh\&.so invocations\&.
.RE
.PP
\fB\-\-ssh\-nullok\fR
.RS 4
Add
\fBnullok\fR
option to all pam_ssh\&.so invocations\&.
.RE
.PP
\fB\-\-ssh\-keyfiles=\fR\fIvalue\fR
.RS 4
Add
\fBkeyfiles=\fR\fIvalue\fR
option to pam_ssh\&.so\&.
.RE
.PP
\fB\-\-sss\fR
.RS 4
Enable/Disable pam_sss\&.so
.RE
.PP
\fB\-\-sss\-debug\fR
.RS 4
Add
\fBdebug\fR
option to all pam_sss\&.so invocations\&.
.RE
.PP
\fB\-\-systemd\fR
.RS 4
Enable/Disable pam_systemd\&.so
.RE
.PP
\fB\-\-systemd\-debug\fR
.RS 4
Add
\fBdebug\fR
option to all pam_systemd\&.so invocations\&.
.RE
.PP
\fB\-\-systemd\-kill_session_processes=\fR\fIvalue\fR
.RS 4
Add
\fBkill_session_processes=\fR\fIvalue\fR
option to pam_systemd\&.so\&.
.RE
.PP
\fB\-\-systemd\-kill_only_users=\fR\fIvalue\fR
.RS 4
Add
\fBkill_only_users=\fR\fIvalue\fR
option to pam_systemd\&.so\&.
.RE
.PP
\fB\-\-systemd\-kill_exclude_users=\fR\fIvalue\fR
.RS 4
Add
\fBkill_exclude_users=\fR\fIvalue\fR
option to pam_systemd\&.so\&.
.RE
.PP
\fB\-\-systemd\-controllers=\fR\fIvalue\fR
.RS 4
Add
\fBcontrollers=\fR\fIvalue\fR
option to pam_systemd\&.so\&.
.RE
.PP
\fB\-\-systemd\-reset_controllers=\fR\fIvalue\fR
.RS 4
Add
\fBreset_controllers=\fR\fIvalue\fR
option to pam_systemd\&.so\&.
.RE
.PP
\fB\-\-thinkfinger\fR
.RS 4
Enable/Disable pam_thinkfinger\&.so
.RE
.PP
\fB\-\-thinkfinger\-debug\fR
.RS 4
Add
\fBdebug\fR
option to all pam_thinkfinger\&.so invocations\&.
.RE
.PP
\fB\-\-umask\fR
.RS 4
Add pam_umask\&.so as optional session module\&.
.RE
.PP
\fB\-\-umask\-debug\fR
.RS 4
Add
\fBdebug\fR
option to all pam_umask\&.so invocations in session management\&.
.RE
.PP
\fB\-\-umask\-silent\fR
.RS 4
Add
\fBsilent\fR
option to all pam_umask\&.so invocations in session management\&.
.RE
.PP
\fB\-\-umask\-usergroups\fR
.RS 4
Add
\fBusergroups\fR
option to all pam_umask\&.so invocations in session management\&.
.RE
.PP
\fB\-\-umask\-umask=\fR\fImode\fR
.RS 4
Add
\fBumask=\fR\fImode\fR
to pam_umask\&.so\&.
.RE
.PP
\fB\-\-unix\fR
.RS 4
Enable/Disable pam_unix\&.so
.RE
.PP
\fB\-\-unix\-debug\fR
.RS 4
Add
\fBdebug\fR
option to all pam_unix\&.so invocations\&.
.RE
.PP
\fB\-\-unix\-audit\fR
.RS 4
Add
\fBaudit\fR
option to all pam_unix\&.so invocations\&.
.RE
.PP
\fB\-\-unix\-nodelay\fR
.RS 4
Add
\fBnodelay\fR
option to all pam_unix\&.so invocations\&.
.RE
.PP
\fB\-\-unix\-nullok\fR
.RS 4
Add
\fBnullok\fR
option to all pam_unix\&.so invocations\&.
.RE
.PP
\fB\-\-unix\-shadow\fR
.RS 4
Add
\fBshadow\fR
option to all pam_unix\&.so invocations\&.
.RE
.PP
\fB\-\-unix\-md5\fR
.RS 4
Add
\fBmd5\fR
option to all pam_unix\&.so invocations\&.
.RE
.PP
\fB\-\-unix\-bigcrypt\fR
.RS 4
Add
\fBbigcrypt\fR
option to all pam_unix\&.so invocations\&.
.RE
.PP
\fB\-\-unix\-sha256\fR
.RS 4
Add
\fBsha256\fR
option to all pam_unix\&.so invocations\&.
.RE
.PP
\fB\-\-unix\-sha512\fR
.RS 4
Add
\fBsha512\fR
option to all pam_unix\&.so invocations\&.
.RE
.PP
\fB\-\-unix\-blowfish\fR
.RS 4
Add
\fBblowfish\fR
option to all pam_unix\&.so invocations\&.
.RE
.PP
\fB\-\-unix\-not_set_pass\fR
.RS 4
Add
\fBnot_set_pass\fR
option to all pam_unix\&.so invocations\&.
.RE
.PP
\fB\-\-unix\-nis\fR
.RS 4
Add
\fBnis\fR
option to all pam_unix\&.so invocations\&.
.RE
.PP
\fB\-\-unix\-broken_shadow\fR
.RS 4
Add
\fBbroken_shadow\fR
option to all pam_unix\&.so invocations\&.
.RE
.PP
\fB\-\-unix\-use_first_pass\fR
.RS 4
Add
\fBuse_first_pass\fR
option to all pam_unix\&.so invocations\&.
.RE
.PP
\fB\-\-unix\-try_first_pass\fR
.RS 4
Add
\fBtry_first_pass\fR
option to all pam_unix\&.so invocations\&.
.RE
.PP
\fB\-\-unix\-remember=\fR\fIvalue\fR
.RS 4
Add
\fBremember=\fR\fIvalue\fR
option to pam_unix\&.so\&.
.RE
.PP
\fB\-\-unix\-rounds=\fR\fIvalue\fR
.RS 4
Add
\fBrounds=\fR\fIvalue\fR
option to pam_unix\&.so\&.
.RE
.PP
\fB\-\-unix\-minlen=\fR\fIvalue\fR
.RS 4
Add
\fBminlen=\fR\fIvalue\fR
option to pam_unix\&.so\&.
.RE
.PP
\fB\-\-unix2\fR
.RS 4
Use pam_unix2\&.so as standard UNIX PAM module\&.
.RE
.PP
\fB\-\-unix2\-nullok\fR
.RS 4
Add
\fBnullok\fR
option to all pam_unix2\&.so invocations\&.
.RE
.PP
\fB\-\-unix2\-debug\fR
.RS 4
Add
\fBdebug\fR
option to all pam_unix2\&.so invocations\&.
.RE
.PP
\fB\-\-unix2\-trace\fR
.RS 4
Add
\fBtrace\fR
option to pam_unix2\&.so\&.
.RE
.PP
\fB\-\-unix2\-none\fR
.RS 4
Add option
\fBnone\fR
to pam_unix2\&.so\&.
.RE
.PP
\fB\-\-unix2\-call_modules=\fR\fImodules,\&.\&.\&.\fR
.RS 4
Add
\fBcall_modules=\fR\fIlist of modules\fR
to pam_unix2\&.so\&.
.RE
.PP
\fB\-\-unix2\-nisdir=\fR\fIpath\fR
.RS 4
Add
\fBnisdir=\fR\fIpath\fR
to pam_unix2\&.so\&.
.RE
.PP
\fB\-\-winbind\fR
.RS 4
Enable/Disable pam_winbind\&.so
.RE
.PP
\fB\-\-winbind\-debug\fR
.RS 4
Add
\fBdebug\fR
option to all pam_winbind\&.so invocations\&.
.RE
.RE
.sp
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
.ps +1
\fBSINGLE SERVICE MODULES\fR
.RS 4
.PP
These modules can only be added to single service files\&. See also
the section called \(lqUSAGE EXAMPLES\(rq\&.
.PP
\fB\-\-ck_connector\fR
.RS 4
Enable/Disable pam_ck_connector\&.so
.RE
.PP
\fB\-\-ck_connector\-debug\fR
.RS 4
Add
\fBdebug\fR
option to all pam_ck_connector\&.so invocations\&.
.RE
.PP
\fB\-\-cryptpass\fR
.RS 4
Enable/Disable pam_cryptpass\&.so
.RE
.PP
\fB\-\-csync\fR
.RS 4
Enable/Disable pam_csync\&.so
.RE
.PP
\fB\-\-csync\-use_first_pass\fR
.RS 4
Add
\fBuse_first_pass\fR
option to all pam_csync\&.so invocations\&.
.RE
.PP
\fB\-\-csync\-try_first_pass\fR
.RS 4
Add
\fBtry_first_pass\fR
option to all pam_csync\&.so invocations\&.
.RE
.PP
\fB\-\-csync\-soft_try_pass\fR
.RS 4
Add
\fBsoft_try_pass\fR
option to all pam_csync\&.so invocations\&.
.RE
.PP
\fB\-\-csync\-nullok\fR
.RS 4
Add
\fBnullok\fR
option to all pam_csync\&.so invocations\&.
.RE
.PP
\fB\-\-csync\-debug\fR
.RS 4
Add
\fBdebug\fR
option to all pam_csync\&.so invocations\&.
.RE
.PP
\fB\-\-csync\-silent\fR
.RS 4
Add
\fBsilent\fR
option to all pam_csync\&.so invocations\&.
.RE
.PP
\fB\-\-lastlog\fR
.RS 4
Enable/Disable pam_lastlog\&.so
.RE
.PP
\fB\-\-lastlog\-debug\fR
.RS 4
Add
\fBdebug\fR
option to all pam_lastlog\&.so invocations\&.
.RE
.PP
\fB\-\-lastlog\-silent\fR
.RS 4
Add
\fBsilent\fR
option to all pam_lastlog\&.so invocations\&.
.RE
.PP
\fB\-\-lastlog\-never\fR
.RS 4
Add
\fBnever\fR
option to all pam_lastlog\&.so invocations\&.
.RE
.PP
\fB\-\-lastlog\-nodate\fR
.RS 4
Add
\fBnodate\fR
option to all pam_lastlog\&.so invocations\&.
.RE
.PP
\fB\-\-lastlog\-nohost\fR
.RS 4
Add
\fBnohost\fR
option to all pam_lastlog\&.so invocations\&.
.RE
.PP
\fB\-\-lastlog\-noterm\fR
.RS 4
Add
\fBnoterm\fR
option to all pam_lastlog\&.so invocations\&.
.RE
.PP
\fB\-\-lastlog\-nowtmp\fR
.RS 4
Add
\fBnowtmp\fR
option to all pam_lastlog\&.so invocations\&.
.RE
.PP
\fB\-\-lastlog\-noupdate\fR
.RS 4
Add
\fBnoupdate\fR
option to all pam_lastlog\&.so invocations\&.
.RE
.PP
\fB\-\-lastlog\-showfailed\fR
.RS 4
Add
\fBshowfailed\fR
option to all pam_lastlog\&.so invocations\&.
.RE
.PP
\fB\-\-loginuid\fR
.RS 4
Enable/Disable pam_loginuid\&.so
.RE
.PP
\fB\-\-loginuid\-require_auditd\fR
.RS 4
Add
\fBrequire_auditd\fR
option to all pam_loginuid\&.so invocations\&.
.RE
.PP
\fB\-\-mount\fR
.RS 4
Enable/Disable pam_mount\&.so
.RE
.RE
.SH "NOTES"
.PP
The configuration for gobal service modules written by pam\-config is ignored by the system if the common\-{account,auth,password,session} symlinks don\*(Aqt point to the common\-{account,auth,password,session}\-pc files\&.
.SH "USAGE EXAMPLES"
.PP
pam\-config \-q \-\-unix
.RS 4
Query state of pam_unix\&.so\&.
.RE
.PP
pam\-config \-a \-\-ldap
.RS 4
Enable ldap authentication\&.
.RE
.PP
pam\-config \-\-service gdm \-a \-\-mount
.RS 4
Enable pam_mount\&.so for service gdm\&.
.RE
.PP
pam\-config \-\-debug \-a \-\-force \-\-umask
.RS 4
Enable pam_umask\&.so whether installed or not, and print debug information during the process\&.
.RE
.SH "SEE ALSO"
.PP
\fBPAM\fR(8),
\fBpam_unix\fR(8),
\fBpam_cracklib\fR(8),
\fBpam_mkhomedir\fR(8),
\fBpam_limits\fR(8),
\fBpam_env\fR(8),
\fBpam_xauth\fR(8),
\fBpam_make\fR(8)
.SH "AUTHOR"
.PP
\fBpam\-config\fR
was written by Thorsten Kukuk <kukuk@thkukuk\&.de>\&.
