/* Copyright (C) 2006 Thorsten Kukuk
   Author: Thorsten Kukuk <kukuk@thkukuk.de>

   This program is free software; you can redistribute it and/or modify
   it under the terms of the GNU General Public License version 2 as
   published by the Free Software Foundation.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program; if not, write to the Free Software Foundation,
   Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.  */


#ifdef HAVE_CONFIG_H
#include <config.h>
#endif

#include <errno.h>
#include <stdio.h>
#include <string.h>
#include <sys/types.h>

#include "pam-config.h"

int
write_config_password (const char *file, config_file_t *conf)
{
  FILE *fp;

  if (debug)
    printf ("*** write_config_password (%s, ...)\n", file);

  /* XXX rename () */

  fp = fopen(file, "w");
  if (fp == NULL)
    {
      fprintf (stderr, _("Cannot create %s: %m\n"),
	       file);
      return -1;
    }

  fprintf (fp, "#%%PAM-1.0\n#\n");
  fprintf (fp, "# This file is autogenerated by pam-config. All changes\n");
  fprintf (fp, "# will be overwritten.\n#\n");
  fprintf (fp, "# Password-related modules common to all services\n#\n");
  fprintf (fp,
	   "# This file is included from other service-specific PAM config files,\n"
	   "# and should contain a list of modules that define  the services to be\n"
	   "# used to change user passwords.\n#\n");


  if (conf->use_pwcheck)
    {
      fprintf (fp, "password\trequired\tpam_pwcheck.so\t");
      if (conf->pwcheck_debug)
	fprintf (fp, "debug ");
      if (conf->pwcheck_nullok)
	fprintf (fp, "nullok ");
      if (conf->pwcheck_cracklib)
	{
	  if (conf->pwcheck_cracklib_path)
	    fprintf (fp, "cracklib=%s ", conf->pwcheck_cracklib_path);
	  else
	    fprintf (fp, "cracklib ");
	}
      if (conf->pwcheck_maxlen)
	fprintf (fp, "maxlen=%d ", conf->pwcheck_maxlen);
      if (conf->pwcheck_minlen)
	fprintf (fp, "minlen=%d ", conf->pwcheck_minlen);
      if (conf->pwcheck_tries)
	fprintf (fp, "tries=%d ", conf->pwcheck_tries);
      if (conf->pwcheck_remember)
	fprintf (fp, "remember=%d ", conf->pwcheck_remember);
      if (conf->pwcheck_nisdir)
	fprintf (fp, "nisdir=%s ", conf->pwcheck_nisdir);
      if (conf->pwcheck_not_set_pass)
	fprintf (fp, "not_set_pass ");
      fprintf (fp, "\n");
    }

  if (conf->use_krb5 || conf->use_ldap)
    fprintf (fp, "password\tsufficient\tpam_unix2.so\t");
  else
    fprintf (fp, "password\trequired\tpam_unix2.so\t");
  if (conf->unix2_nullok)
    fprintf (fp, "nullok ");
  if (conf->use_pwcheck)
    fprintf (fp, "use_first_pass use_authtok ");
  if (conf->unix2_debug)
    fprintf (fp, "debug ");
  if (conf->unix2_not_set_pass)
    fprintf (fp, "not_set_pass ");
  if (conf->unix2_call_modules)
    fprintf (fp, "call_modules=%s ", conf->unix2_call_modules);
  fprintf (fp, "\n");

  if (conf->use_make)
    {
      fprintf (fp, "password\toptional\tpam_make.so\t");
      if (conf->make_options)
	fprintf (fp, "%s ", conf->make_options);
      fprintf (fp, "\n");
    }

  if (conf->use_krb5)
    {
      if (conf->use_ldap)
	fprintf (fp, "password\tsufficient\tpam_krb5.so\tuse_first_pass use_authtok ");
      else
	fprintf (fp, "password\trequired\tpam_krb5.so\tuse_first_pass use_authtok ");

      if (conf->krb5_debug)
        fprintf (fp, "debug ");
      fprintf (fp, "\n");
    }

  if (conf->use_ldap)
    {
      fprintf (fp, "password\trequired\tpam_ldap.so\tuse_first_pass use_authtok ");
      if (conf->ldap_debug)
        fprintf (fp, "debug ");
      fprintf (fp, "\n");
    }

  fclose (fp);

  return 0;
}
