/* Copyright (C) 2006, 2007 Thorsten Kukuk
   Author: Thorsten Kukuk <kukuk@thkukuk.de>

   This program is free software; you can redistribute it and/or modify
   it under the terms of the GNU General Public License version 2 as
   published by the Free Software Foundation.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program; if not, write to the Free Software Foundation,
   Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.  */


#ifdef HAVE_CONFIG_H
#include <config.h>
#endif

#include <errno.h>
#include <stdio.h>
#include <string.h>
#include <sys/types.h>

#include "pam-config.h"

int
write_config_password (const char *file, pam_module_t **module_list)
{
  FILE *fp;

  if (debug)
    printf ("*** write_config_password (%s, ...)\n", file);

  /* XXX rename () */

  fp = fopen(file, "w");
  if (fp == NULL)
    {
      fprintf (stderr, _("Cannot create %s: %m\n"),
	       file);
      return -1;
    }

  fprintf (fp, "#%%PAM-1.0\n#\n");
  fprintf (fp, "# This file is autogenerated by pam-config. All changes\n");
  fprintf (fp, "# will be overwritten.\n#\n");
  fprintf (fp, "# Password-related modules common to all services\n#\n");
  fprintf (fp,
	   "# This file is included from other service-specific PAM config files,\n"
	   "# and should contain a list of modules that define  the services to be\n"
	   "# used to change user passwords.\n#\n");

  pam_module_t **modptr = module_list;

  while (*modptr != NULL)
    {
      (*modptr)->write_config (*modptr, PASSWORD, fp);
      ++modptr;
    }

#if 0

  if (conf->use_winbind)
    {
      fprintf (fp, "password\tsufficient\tpam_winbind.so\t");
      if (conf->winbind_debug)
        fprintf (fp, "debug ");
      fprintf (fp, "\n");
    }

  if (conf->use_pwcheck)
    {
      fprintf (fp, "password\trequisite\tpam_pwcheck.so\t");
      if (conf->pwcheck_debug)
	fprintf (fp, "debug ");
      if (conf->pwcheck_nullok)
	fprintf (fp, "nullok ");
      if (conf->pwcheck_cracklib)
	{
	  if (conf->pwcheck_cracklib_path)
	    fprintf (fp, "cracklib=%s ", conf->pwcheck_cracklib_path);
	  else
	    fprintf (fp, "cracklib ");
	}
      if (conf->pwcheck_maxlen)
	fprintf (fp, "maxlen=%d ", conf->pwcheck_maxlen);
      if (conf->pwcheck_have_minlen)
	fprintf (fp, "minlen=%d ", conf->pwcheck_minlen);
      if (conf->pwcheck_tries)
	fprintf (fp, "tries=%d ", conf->pwcheck_tries);
      if (conf->pwcheck_remember)
	fprintf (fp, "remember=%d ", conf->pwcheck_remember);
      if (conf->pwcheck_no_obscure_checks)
	fprintf (fp, "no_obscure_checks ");
      if (conf->pwcheck_nisdir)
	fprintf (fp, "nisdir=%s ", conf->pwcheck_nisdir);
      fprintf (fp, "\n");
    }
  else if (conf->use_cracklib)
    {
      fprintf (fp, "password\trequisite\tpam_cracklib.so\t");
      if (conf->cracklib_debug)
	fprintf (fp, "debug ");
      if (conf->cracklib_dictpath)
	fprintf (fp, "dictpath=%s ", conf->cracklib_dictpath);
      if (conf->cracklib_retry)
	fprintf (fp, "retry=%d ", conf->cracklib_retry);
      fprintf (fp, "\n");
    }

  // if (conf->use_krb5 || conf->use_ldap || conf->use_lum)
  //   fprintf (fp, "password\tsufficient\tpam_unix2.so\t");
  // else
  //   fprintf (fp, "password\trequired\tpam_unix2.so\t");
  // if (conf->unix2_nullok)
  //   fprintf (fp, "nullok ");
  // if (conf->use_pwcheck || conf->use_cracklib)
  //   fprintf (fp, "use_authtok ");
  // if (conf->unix2_debug)
  //   fprintf (fp, "debug ");
  // if (conf->unix2_call_modules)
  //   fprintf (fp, "call_modules=%s ", conf->unix2_call_modules);
  // fprintf (fp, "\n");

  if (conf->use_make)
    {
      fprintf (fp, "password\toptional\tpam_make.so\t");
      if (conf->make_options)
	fprintf (fp, "%s ", conf->make_options);
      fprintf (fp, "\n");
    }

  if (conf->use_krb5)
    {
      if (conf->use_ldap || conf->use_lum)
	fprintf (fp, "password\tsufficient\tpam_krb5.so\tuse_authtok ");
      else
	fprintf (fp, "password\trequired\tpam_krb5.so\tuse_authtok ");

      if (conf->krb5_debug)
        fprintf (fp, "debug ");
      if (conf->krb5_minuid)
	fprintf (fp, "minimum_uid=%u ", conf->krb5_minuid);
      fprintf (fp, "\n");
    }

  if (conf->use_ldap)
    {
      fprintf (fp, "password\trequired\tpam_ldap.so\ttry_first_pass use_authtok ");
      if (conf->ldap_debug)
        fprintf (fp, "debug ");
      fprintf (fp, "\n");
    }

  if (conf->use_lum)
    fprintf (fp, "password\trequired\tpam_nam.so\ttry_first_pass\n");

#endif

  fclose (fp);

  return 0;
}
